#include "6step_definitions.h"

const six_step_sector_control_t six_step_sector_positive_control_table[] = {
    {SIX_STEP_CONTROL_ACTION_FLOAT, SIX_STEP_CONTROL_ACTION_LOW, SIX_STEP_CONTROL_ACTION_HIGH},
    {SIX_STEP_CONTROL_ACTION_HIGH, SIX_STEP_CONTROL_ACTION_LOW, SIX_STEP_CONTROL_ACTION_FLOAT},
    {SIX_STEP_CONTROL_ACTION_HIGH, SIX_STEP_CONTROL_ACTION_FLOAT, SIX_STEP_CONTROL_ACTION_LOW},
    {SIX_STEP_CONTROL_ACTION_FLOAT, SIX_STEP_CONTROL_ACTION_HIGH, SIX_STEP_CONTROL_ACTION_LOW},
    {SIX_STEP_CONTROL_ACTION_LOW, SIX_STEP_CONTROL_ACTION_HIGH, SIX_STEP_CONTROL_ACTION_FLOAT},
    {SIX_STEP_CONTROL_ACTION_LOW, SIX_STEP_CONTROL_ACTION_FLOAT, SIX_STEP_CONTROL_ACTION_HIGH},
};

const six_step_sector_control_t six_step_sector_negative_control_table[] = {
    {SIX_STEP_CONTROL_ACTION_FLOAT, SIX_STEP_CONTROL_ACTION_HIGH, SIX_STEP_CONTROL_ACTION_LOW},
    {SIX_STEP_CONTROL_ACTION_HIGH, SIX_STEP_CONTROL_ACTION_FLOAT, SIX_STEP_CONTROL_ACTION_LOW},
    {SIX_STEP_CONTROL_ACTION_HIGH, SIX_STEP_CONTROL_ACTION_LOW, SIX_STEP_CONTROL_ACTION_FLOAT},
    {SIX_STEP_CONTROL_ACTION_FLOAT, SIX_STEP_CONTROL_ACTION_LOW, SIX_STEP_CONTROL_ACTION_HIGH},
    {SIX_STEP_CONTROL_ACTION_LOW, SIX_STEP_CONTROL_ACTION_FLOAT, SIX_STEP_CONTROL_ACTION_HIGH},
    {SIX_STEP_CONTROL_ACTION_LOW, SIX_STEP_CONTROL_ACTION_HIGH, SIX_STEP_CONTROL_ACTION_FLOAT},
};