
#include "cordic_trig_generated.h"

#include <stddef.h>

/**
 * Generated by Sahil's Cordic Trig Generator: https://github.com/sahil-kale/cordic-trig-generator
 */

#define ATAN_TABLE_SIZE 32
#define FIXED_POINT_SCALING_FACTOR 1073741824  // (1 << 30)
#define ONE_OVER_FIXED_POINT_SCALING_FACTOR (1.0F / (float)FIXED_POINT_SCALING_FACTOR)
#define COS_K1 652032874  // 0.6072529350088814 scaled by FIXED_POINT_SCALING_FACTOR
#define M_PI_FLOAT 3.14159265F

static const cordic_trig_fixed_point_t ATAN_TABLE[ATAN_TABLE_SIZE] = {
    843314856L, 497837829L, 263043836L, 133525158L, 67021686L, 33543515L, 16775850L, 8388437L, 4194282L, 2097149L, 1048575L,
    524287L,    262143L,    131071L,    65535L,     32767L,    16383L,    8191L,     4095L,    2047L,    1023L,    511L,
    255L,       127L,       63L,        31L,        15L,       8L,        4L,        2L,       1L,       0L};

void cordic_trig_get_sin_cos(float theta_rad, float *sin_val, float *cos_val) {
    cordic_trig_fixed_point_t x = COS_K1;
    cordic_trig_fixed_point_t y = 0;

    float sin_multiplier = 1.0F;
    float cos_multiplier = 1.0F;

    if (theta_rad >= (M_PI_FLOAT / 2) && (theta_rad < M_PI_FLOAT)) {
        theta_rad = M_PI_FLOAT - theta_rad;
        cos_multiplier = -1.0F;  // Since cos(pi - x) = -cos(x)
    } else if (theta_rad >= M_PI_FLOAT && (theta_rad < 3 * M_PI_FLOAT / 2)) {
        theta_rad = theta_rad - M_PI_FLOAT;
        sin_multiplier = -1.0F;  // Since sin(pi + x) = -sin(x)
        cos_multiplier = -1.0F;  // Since cos(pi + x) = -cos(x)
    } else if (theta_rad >= 3 * M_PI_FLOAT / 2 && (theta_rad < 2 * M_PI_FLOAT)) {
        theta_rad = 2 * M_PI_FLOAT - theta_rad;
        sin_multiplier = -1.0F;  // Since sin(2pi - x) = -sin(x)
    } else {
        // Just chill
    }

    cordic_trig_fixed_point_t z = (cordic_trig_fixed_point_t)(theta_rad * (float)FIXED_POINT_SCALING_FACTOR);

    for (size_t i = 0; i < ATAN_TABLE_SIZE; i++) {
        cordic_trig_fixed_point_t x_new = x;
        cordic_trig_fixed_point_t y_new = y;

        if (z >= 0) {
            x_new = x - (y >> i);
            y_new = y + (x >> i);
            z -= ATAN_TABLE[i];
        } else {
            x_new = x + (y >> i);
            y_new = y - (x >> i);
            z += ATAN_TABLE[i];
        }

        x = x_new;
        y = y_new;
    }

    if (cos_val) {
        *cos_val = (float)x * ONE_OVER_FIXED_POINT_SCALING_FACTOR * cos_multiplier;
    }

    if (sin_val) {
        *sin_val = (float)y * ONE_OVER_FIXED_POINT_SCALING_FACTOR * sin_multiplier;
    }
}
