
#ifndef CORDIC_TRIG_GENERATED_H
#define CORDIC_TRIG_GENERATED_H

/**
 * Generated by Sahil's Cordic Trig Generator: https://github.com/sahil-kale/cordic-trig-generator
 */

#include <stdint.h>

typedef int32_t cordic_trig_fixed_point_t;

/**
 * @brief Get the sine and cosine values of the given angle in radians
 *
 * @param theta_rad Angle in radians
 * @param sin_val Pointer to the sine value
 * @param cos_val Pointer to the cosine value
 */
void cordic_trig_get_sin_cos(float theta_rad, float *sin_val, float *cos_val);

#endif  // CORDIC_TRIG_GENERATED_H
